### ISSUE TITLE
Feature request: update PettingZoo version

### ISSUE THREAD

**Issue by elliottower** [AIRI-Institute/pogema#19]
Hi, would it be possible to update this repo to use the most recent version of PettingZoo? We want to list this project in PettingZoo's [third-party-environments](https://pettingzoo.farama.org/environments/third_party_envs/), but we can only include environments which work with the current version. 

If you need any help working out issues due to different versions feel free to ask, there were some breaking changes in version 1.2, so it requires a bit of code changes to adapt. The previous API returned `done` in the step() function, whereas the new one returns truncated and terminated (matching gymnasium). There is a migration guide for gymnasium explaining the changes further, the steps should be basically the same (we're working on making resources for updating old PettingZoo repositories as well): https://gymnasium.farama.org/content/migration-guide/

**Comment by Tviskaron** [comment]
Hi Elliot! Thank you for your suggestion. I have completed the transfer to the new version of Gymnasium/PettingZoo in [6132bcd2e18a0](https://github.com/AIRI-Institute/pogema/commit/996cc4743c4784e6e438ab89a476132bcd2e18a0)

**Comment by elliottower** [comment]
> @elliottower

Thanks for the update, I meant to reply here but I updated the doc to include this project. If you go to this page and select main (unstable) it shows up second in the list (sorted by number of stars) https://pettingzoo.farama.org/main/environments/third_party_envs/
