### ISSUE TITLE
How to get the big map from the environment?

### ISSUE THREAD

**Issue by Arseni1919** [AIRI-Institute/pogema#20]
I want to plot the global map with agents though `matplotlib`. How can I do that? Thank you.
```python
from pogema import pogema_v0, Hard8x8


def main():
    env = pogema_v0(grid_config=Hard8x8())
    my_map = Hard8x8()  # there is no map inside :(
    obs = env.reset()

    while True:
        # Using random policy to make actions
        obs, reward, terminated, info = env.step(env.sample_actions())
        env.render()
        if all(terminated):
            break
```

**Comment by Tviskaron** [comment]
You can plot SVG animation with AnimationMonitor wrapper, as show in https://colab.research.google.com/drive/19dSEGTQeM3oVJtVjpC162t1XApmv6APc?usp=sharing#scrollTo=n68FdCRf1Umv (e.g. for you case it could be static image, using static=True option in config)

**Comment by Arseni1919** [comment]
I want to show also the additional things on the graph. Just an image of SVG of JPEG does not help, unfortunatelly. 
I need some sort of numpy array or matrix or list of lists that represents the map, similar to what you output as observations to the agents, but the global one. **How it is possible to get it?**
Another issue, **how can I get the global positions of agents?** (global position on the global map)
Thank you.
