### ISSUE TITLE
Run the algorithms

### ISSUE THREAD

**Issue by Arseni1919** [AIRI-Institute/pogema#21]
**Can you provide a small example of running the baseline algorithms without docker or additional projects, please?**
It is ok for me to run the learning phase by myself. I just want to keep everything as simple as possible and I want to create my own algorithms to compare with yours. Thank you in advance.

**Comment by Tviskaron** [comment]
First of all, the simplest agent is the A* agent. You can use the BatchAStarAgent from https://github.com/AIRI-Institute/pogema/blob/main/pogema/a_star_policy.py, which predicts a batch of actions based on observation.

Second, you can compare your approach with a single-agent trained with SB3, as shown in this example: https://colab.research.google.com/drive/1vPwTd0PnzpWrB-bCHqoLSVwU9G9Lgcmv?usp=sharing

And third, you can use https://github.com/Tviskaron/pogema-baselines/tree/main/appo to train the agent. Docker is optional for training this agent, but the experiment is computationally intensive.

**Comment by Arseni1919** [comment]
I wil try to play with first and second options. Thanks.

**Comment by Arseni1919** [comment]
The first option with A* has the following method:
```python
def act(self, obs):
   xy, target_xy, obstacles, agents = obs['xy'], obs['target_xy'], obs['obstacles'], obs['agents']
```
And the `obs' of the environment is just a three matricies. 
What can I do in order to use the algorithm?

**Comment by Tviskaron** [comment]
To access global state you should create env with `observation_type=MAPF`option in `GridConfig`. A* agent works with this observation.

**Comment by Tviskaron** [comment]
Here is an example: 

```
from pogema import pogema_v0, GridConfig
from pogema.animation import AnimationMonitor, AnimationConfig

# Define random configuration
grid_config = GridConfig(num_agents=4,  # number of agents
                         size=8, # size of the grid
                         density=0.4,  # obstacle density
                         seed=1,  # set to None for random 
                                  # obstacles, agents and targets 
                                  # positions at each reset
                         max_episode_steps=128,  # horizon
                         obs_radius=3,  # defines field of view
                         observation_type='MAPF'
                         )

env = pogema_v0(grid_config=grid_config)
env = AnimationMonitor(env)

obs, info = env.reset()

print(obs)
```

**Comment by Arseni1919** [comment]
It's working! Great, thanks!

**Comment by Arseni1919** [comment]
What is the difference between POMAPF and MAPF observation_type? Is the POMAPF the case that is described in the paper? 
What is the default state?..
