### ISSUE TITLE
Goal positon is far away from the agent

### ISSUE THREAD

**Issue by Arseni1919** [AIRI-Institute/pogema#22]
if goal position is far away from the agent (out of the observation area), what is represented by the third layer of the observation? How can agent understand where to move?

**Comment by Tviskaron** [comment]
In this case, the environment provides a projection of the target, as highlighted in Figure 2 of https://doi.org/10.48550/arxiv.2206.10944.

**Comment by Arseni1919** [comment]
Thank you!
