### ISSUE TITLE
The example in README.md is incorrect

### ISSUE THREAD

**Issue by Arseni1919** [AIRI-Institute/pogema#23]
- the `env.reset()` returns only obs (without info)
- the `env.step()` returns  obs, reward, terminated, info and not  obs, reward, terminated, truncated, info
```python
from pogema import pogema_v0, Hard8x8


def main():
    env = pogema_v0(grid_config=Hard8x8())
    obs = env.reset()  # here

    while True:
        # Using random policy to make actions
        obs, reward, terminated, info = env.step(env.sample_actions())  # and here
        env.render()
        if all(terminated):
            break


if __name__ == '__main__':
    main()
```

**Comment by Tviskaron** [comment]
You probably used a version of Pogema from PyPI. The recommended way to interact with Gymnasium (instead of GYM) will be introduced in the next major release. If you want to install the latest version from the repository, please use `pip install git+https://github.com/AIRI-Institute/pogema.git`

**Comment by Arseni1919** [comment]
Nooo, please support your own sepparate implementation apart from gym and gymnasium! They are terrible, always changing their API. Mac computers struggle all the time with their infinite bugs. Yours will be far more stable. I like it. No additional layes - keep it simple.
