### ISSUE TITLE
How to choose map in Pymarl style?

### ISSUE THREAD

**Issue by 98luobo** [AIRI-Institute/pogema#28]
Hi,
How to choose map in pymarl style code?

**Comment by Tviskaron** [comment]
Hi! Could you please clarify what you specifically mean by "PyMARL style"?

**Comment by 98luobo** [comment]
`from pogema import pogema_v0, GridConfig

env = pogema_v0(GridConfig(integration="PyMARL"))`

**Comment by Tviskaron** [comment]
For PyMARL integration, selecting a map can be achieved similarly to how it is done in the original example with a custom map: 

```python3
from pogema import pogema_v0, GridConfig

grid = """
.....#.....
.....#.....
...........
.....#.....
.....#.....
#.####.....
.....###.##
.....#.....
.....#.....
...........
.....#.....
"""

# Define new configuration with 8 randomly placed agents and PyMARL integration
grid_config = GridConfig(map=grid, num_agents=8, integration="PyMARL")

# Create custom Pogema environment
env = pogema_v0(grid_config=grid_config)
```

**Comment by 98luobo** [comment]
I have solved the problem of changing the map, it works fine in 8X8 and 16X16, but when I run 32X32 and 64X64, the program is killed by the system. I don't know if you have such a question? (No error output, directly Killed)

**Comment by Tviskaron** [comment]
I'm closing this issue as the initial problem related to creating the config appears to be resolved. The discussion regarding the subsequent issue has been moved to https://github.com/Tviskaron/pogema-baselines/issues/10.
