### ISSUE TITLE
Custom observation

### ISSUE THREAD

**Issue by johnnyhoichuen** [AIRI-Institute/pogema#29]
Is it possible to generate custom observation like this?
[[obstacles in agent's FOV], [other agents in agent's FOV], [guide to destination]]

At the end I hope to implement a similar environment defined in this [paper](https://arxiv.org/pdf/2106.11365.pdf) (V. B. Observation representation):
[Reference of the code](https://github.com/ZiyuanMa/DHC/blob/master/environment.py#L422)

Thanks a lot!

**Comment by Tviskaron** [comment]
Sorry for the delayed response; I missed your question earlier. Yes, it is possible to generate a custom field of view (FOV) as you described. Pogema already provides observations for obstacles and other agents within the agent's FOV. As for the 'guide to the destination' component, it could be implemented as a wrapper over the existing environment. If you need the full state of the environment to create this information, it is also possible using methods like get_obstacles, get_agents_xy, and get_targets_xy. Let me know if you need further details on how to implement this!

**Comment by johnnyhoichuen** [comment]
Thank you for your reply!! For wrapper do you mean a class extending it or I'll have to use some other predefined classes?

**Comment by Tviskaron** [comment]
I mean a class that extends ObservationWrapper or Wrapper in the Gym/Gymnasium framework. An example of such a wrapper can be found at https://github.com/AIRI-Institute/when-to-switch/blob/main/learning/grid_memory.py. In this example, you can see the class GridMemoryWrapper that extends gym.ObservationWrapper. Although it uses an older version of Pogema (with Gym, instead Gymnasium), the logic is quite similar.
